[package]
name = "consumet-api-rs"
version = "0.1.2"
edition = "2021"
description = "Consumet API RIIR"
license-file = "LICENSE"
respository = "https://github.com/carrotshniper21/consumet-api-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
anyhow = "1.0"
chrono = "0.4.26"
futures = "0.3.28"
md5 = "0.7.0"
openssl = "0.10.55"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
scraper = "0.17.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = ["full"] }
